name: mtodo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  easy_dynamic_theme: ^2.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  responsive_sizer: ^3.3.0+1
  riverpod_annotation: ^2.3.4
  skeletonizer: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
